-- Membership applications are accessed only through the application's
-- server-side Supabase secret-key client. No direct browser policies are added.
create table if not exists public.membership_applications (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) >= 2),
  email text not null check (position('@' in email) > 1),
  phone text not null check (char_length(trim(phone)) >= 7),
  status text not null default 'pending' check (status in ('pending', 'approved', 'active')),
  activation_code_hash text,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  activated_at timestamptz
);

create index if not exists membership_applications_email_idx
  on public.membership_applications (email);

create index if not exists membership_applications_status_idx
  on public.membership_applications (status);

alter table public.membership_applications enable row level security;

comment on table public.membership_applications is
  'Membership applications. Access is limited to the application server using a Supabase secret key.';
